server:
  applicationConnectors:
    - type: http
      port: 7060
  adminConnectors:
    - type: http
      port: 7061

bitBucketServerName: {serverName}
bitBucketServerPort: {serverPort}

jenkinsServerUrl: {serverUrl}
jenkinsJobTemplateFile: {templateFile}
