server:
  applicationConnectors:
    - type: http
      port: 7060
  adminConnectors:
    - type: http
      port: 7061

bitBucket:
  bitBucketServerName: bitbucket
  bitBucketServerPort: 80

jenkins:
  jenkinsServerUrl: http://jenkins:80/jenkings
  jenkinsJobTemplateFile: src/test/resources/test-job-template/empty-job.xml

sonar:
  sonarUrl: http://sonar:80
  user: user
  password: password

svn:
  host: svn
  port: 81